url: http://www.flowerybag.com

title: FLOWERYBAG

keywords: FLOWERYBAG

description: FLOWERYBAG

address: 1356-1358 Jiefang North Road,Baiyun District,China

email: customerservice1@flowerybag.com

facebook: https://www.facebook.com/fei.lu.12914216

youtube: https://www.youtube.com/channel/UCDQzzJo-HF6aP9iljxwbRyg

instagram: https://instagram.com/gilehriyaand?r=nametag

exclude:
  - README.md
  - style.css
